---
version: 2.1

orbs:
  rust: twdps/rust-api@2.11.0
  cosign: twdps/cosign@0.1.0
  kube: twdps/kube-ops@0.3.0
  op: twdps/onepassword@1.0.0


# ==== global pipeline parameters 

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: cohorts
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail
  registry:
    description: publish to this registry
    type: string
    default: ghcr.io/twks-cohort
  executor-image:
    description: image to use for local jobs
    type: string
    default: twdps/circleci-kube-ops:alpine-0.7.0

# ==== triggers 

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:
  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: cluster environment
        type: string
      source-env:
        description: .env file to source into BASH_ENV
        type: string
    steps:
      - op/env:
          env-file: << parameters.source-env >>
  set-kubeconfig:
    parameters:
      cluster:
        description: cluster to configure
        type: string
    steps:
      - run:
          name: setup kubeconfig
          command: |
            mkdir -p ~/.kube
            ENV=<< parameters.cluster >> op inject -i tpl/kubeconfig.tpl -o ~/.kube/config


workflows:
  version: 2

  development-build:
    jobs:
      - rust/secure-image-build:
          name: secure-build
          context: << pipeline.parameters.context >>
          shell: /bin/bash
          before-build:
            - run:
                name: inject environment variables
                command: |
                  op inject -i op.env -o $BASH_ENV
                  source $BASH_ENV
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          registry: << pipeline.parameters.registry >>
          image: five-lab-basic-bot
          image-cve-scan: false
          skip-base-image: true
          snyk-organization: twdps
          port-definition: "8000:8000"
          after-push:
            - cosign/install:
                cosign-version: v2.0.2
            - run:
                name: Confirm Docker registry credentials are configured and correct
                command: |
                  echo 'write to .docker/config.json is secure in ephemeral runtime environment'
                  echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_LOGIN} --password-stdin << pipeline.parameters.registry >>
            - run:
                name: Confirm signing parameters are set; key path, COSIGN_PASSWORD
                command: |
                  if [ ! -f cosign.key ]; then
                    echo "signing key not available; not able to sign image."
                    exit 1
                  fi
                  if [ ! -f cosign.pub ]; then
                    echo "verification key not available; not able to validate signing process."
                    exit 1
                  fi
                  if [ ! ${COSIGN_PASSWORD-} ]; then
                    echo "signing key passphrase is not available; not able to sign image."
                    exit 1
                  fi
            - run:
                name: Sign oci image and store signature to registry
                command: |
                  cosign sign -y --key cosign.key \
                      << pipeline.parameters.registry >>/five-lab-basic-bot:dev.${CIRCLE_SHA1:0:7}
            - run:
                name: verify signature using public key
                command: |
                  cosign verify --key cosign.pub << pipeline.parameters.registry >>/five-lab-basic-bot:dev.${CIRCLE_SHA1:0:7}
          filters: *on-push-main

  development-deploy-wip:
    jobs:
      - deploy:
          context: << pipeline.parameters.context >>
          shell:  op run --env-file op.nonprod.env -- /bin/bash -eo pipefail
          name: Deploy to Dev Namespace
          cluster: nonprod-us-east-2
          environment: nonprod
          source-env: op.nonprod.env

jobs:
  deploy:
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << parameters.shell >>
    parameters:
      shell:
        description: shell option directive
        type: string
        default: /bin/bash -eo pipefail
      cluster:
        description: target kubernetes cluster
        type: string
      environment:
        description: values environment to use
        type: string
      source-env:
        description: .env file to source into BASH_ENV
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
          source-env: << parameters.source-env >>
      - set-kubeconfig:
          cluster: << parameters.cluster >>
      - run:
          name: Inject Docker config
          command: |
            op inject -i ./chart/docker-config.json.tpl -o ./chart/docker-config.json
      - run:
          name: Deploy via Helm
          command: |
            helm upgrade \
            --install \
            --namespace team-five<< parameters.environment >> \
            --values deployment/values-<< parameters.environment >>.yaml \
            --cleanup-on-fail \
            --atomic \
            five-lab-basic-bot \
            ./chart
