apiVersion: apps/v1
kind: Deployment
metadata:
  name: five-lab-basic-bot
  labels:
    app: five-lab-basic-bot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: five-lab-basic-bot 
  template:
    metadata:
      labels:
        app: five-lab-basic-bot 
    spec:
      containers:
      - name: five-lab-basic-bot
        image: ghcr.io/twks-cohort/five-lab-basic-bot:latest
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: DISCORD_TOKEN
